version: '3.8'

services:
  db:
    container_name: db
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shopper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d shopper"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/shopper
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "
      npm run build &&
      npm run seed &&
      npm run dev
      "
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://backend:8080